# Configuration file for SimpleChestShop plugin

# Material to be used for shop chests.
shop_chest_material: CHEST

shop_identifier_sign_text: "[Shop]"

shop_currency_type: "EMERALD"

default_buy_price: 10

default_sell_price: 5

allow_admin_shops: true

# GUI Configuration
gui_title: "&aChest Shop"
gui_size: 27  # Size of the inventory (9, 18, 27, 36, 45, or 54)
default_items:
  0: DIAMOND
  1: IRON_INGOT
  2: GOLD_INGOT
  3: EMERALD
  4: APPLE
  5: BREAD
  6: POTION
  7: STONE

purchase_item: "APPLE" #set this as default

# Messages
message_shop_created: "&aShop created for {item}"
message_admin_shop_created: "&aAdmin shop created for {item}"
message_no_permission: "&cYou do not have permission to perform this action."
message_invalid_arguments: "&cInvalid arguments. Usage: {usage}"

# Currency
currency_symbol: "$"

# Feature Toggles
enable_towny_integration: true
enable_luckperms_integration: true
enable_geyser_integration: true
enable_floodgate_integration: true
