# SimpleChestShop Configuration

settings:
  enable_shop_creation: true
  debug_mode: false

messages:
  shop_detected: "§a[Shop] System: Shop sign detected and enabled!"
  no_shop_permission: "§c[Shop] System: You do not have permission to create shops."
  shop_must_be_in_town: "§c[Shop] System: Shops can only be created within town boundaries."

towny:
  enable_towny_integration: true
  require_town: false

permissions:
  enable_permissions: true
  create_shop_permission: "chestshop.create"

vault:
  enable_vault_integration: true # Master switch for Vault integration

  # Add more Vault settings here later

  # Add more permissions here as we develop the plugin

  # Add more settings here as we develop the plugin

  # Add more insanity as y'all learn I dont know how to code LMAO. I'm just a writer.


  # Add more Towny settings here later

  # Add more messages here as we develop the plugin