# Configuration file for SimpleChestShop plugin

# Material to be used for shop chests.
shop_chest_material: CHEST  # The type of block that will act as the shop chest.

shop_identifier_sign_text: "[Shop]"  # The text that identifies a block as a shop.

shop_currency_type: "EMERALD"  # The currency type used for transactions in the shop.

default_buy_price: 10  # Default price for purchasing items from the shop.
default_sell_price: 5  # Default price for selling items to the shop.

allow_admin_shops: true  # Allows admins to create shops.

# GUI Configuration
gui_title: "&aChest Shop"  # Title displayed on the shop GUI.
gui_size: 27  # Size of the inventory (9, 18, 27, 36, 45, or 54).

# Default items to be displayed in the shop GUI.
default_items:
  0: DIAMOND
  1: IRON_INGOT
  2: GOLD_INGOT
  3: EMERALD
  4: APPLE
  5: BREAD
  6: POTION
  7: STONE

purchase_item: "APPLE"  # Default item for purchase in the shop.

# Messages displayed to the player
message_shop_created: "&aShop created for {item}"  # Message when a shop is successfully created.
message_admin_shop_created: "&aAdmin shop created for {item}"  # Message for admin-created shops.
message_no_permission: "&cYou do not have permission to perform this action."  # Message for permission denial.
message_invalid_arguments: "&cInvalid arguments. Usage: {usage}"  # Message for invalid command usage.
message_items_added: "&aAdded {quantity} {item} to your shop."
message_items_removed: "&aRemoved {items} from your shop."
message_items_updated: "&aUpdated {item} in your shop to quantity {quantity} and price ${price}."
message_invalid_quantity: "&cQuantity must be a positive integer."
message_invalid_price: "&cPrice must be a non-negative number."

# Currency settings
currency_symbol: "$"  # Symbol used to represent currency in the shop.

# Feature Toggles
enable_towny_integration: true  # Enables integration with Towny plugin.
enable_vault_integration: true  # Enables integration with Vault plugin.
enable_luckperms_integration: true  # Enables integration with LuckPerms plugin.
